spring.application.name=file-portal
# H2 Console ko enable karne ke liye
spring.h2.console.enabled=true
# Console ka rasta (Default yahi hota hai)
spring.h2.console.path=/h2-console
# Database ka permanent address (Memory mein)
spring.datasource.url=jdbc:h2:mem:testdb